# Generated by Django 4.2.16 on 2024-10-10 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Register',
            new_name='RegisterE',
        ),
    ]
